freebsd_instance:
  image_family: freebsd-13-0-snap

task:
  install_script: pkg install -y git
  script:
    - git clone https://github.com/freebsd/freebsd.git
    - git clone https://github.com/sobomax/makeself.git
    - ls
