freebsd_instance:
  image_family: freebsd-13-0-snap

task:
  timeout_in: 120m
  install_script:
    - pkg install -y git ccache
    - git clone https://github.com/freebsd/freebsd.git
    - git clone https://github.com/sobomax/makeself.git
  build_cache:
    folder: /usr/obj
  script:
    - make -C freebsd CFLAGS="-O0 -pipe" WITHOUT_KERNEL_SYMBOLS=yes WITHOUT_TOOLCHAIN=yes WITHOUT_TESTS=yes WITHOUT_DEBUG_FILES=yes buildkernel
    - cd freebsd
    - env WITHOUT_KERNEL_SYMBOLS=yes WITHOUT_TOOLCHAIN=yes WITHOUT_TESTS=yes WITHOUT_DEBUG_FILES=yes ../distribution
    - env WITHOUT_KERNEL_SYMBOLS=yes WITHOUT_TOOLCHAIN=yes WITHOUT_TESTS=yes WITHOUT_DEBUG_FILES=yes ../installkernel
