#!/bin/sh

set -e
#set -x

BASEDIR="${BASEDIR:-$(dirname -- $0)}"
BASEDIR="`readlink -f -- "${BASEDIR}"`"

tempfoo=`basename "${0}"`

. "${BASEDIR}/makeargs/${tempfoo}.sub"

DESTDIR="`mktemp -d -t "${tempfoo}"`" || exit 1
export DESTDIR

WRAPDIR="`mktemp -d "${DESTDIR}/${tempfoo}.wrap"`" || exit 1
export WRAPDIR

WSNAME="install.sh"

WRAPSCRIPT="${WRAPDIR}/${WSNAME}"
export WRAPSCRIPT

echo "set -e" > "${WRAPSCRIPT}"
chmod 755 "${WRAPSCRIPT}"

IFS=$'\n'
MAKE_ARGS=`gen_make_args`
if [ "${tempfoo}" = "distribution" ]
then
  make ${MAKE_ARGS} WITHOUT_PROFILE=y WITHOUT_DEBUG_FILES=y \
   WITHOUT_TESTS=y WITHOUT_MAN=y WITHOUT_INCLUDES=y \
   INSTALL="${BASEDIR}/wrappers/gencmd echo" \
   DESTDIR="${DESTDIR}" installworld
  echo "set -e" > "${WRAPSCRIPT}"
fi
make ${MAKE_ARGS} DESTDIR="${DESTDIR}" "${@}" "${tempfoo}"
chmod 755 "${WRAPDIR}"

echo "echo \"${tempfoo} completed successfully.\"" >> "${WRAPSCRIPT}"

COMPRESS_CMD="xz -T0 -v" UNCOMPRESS_CMD="xz -T0 -d" /usr/home/sobomax/projects/makeself/makeself.sh \
 --xz --tar-quietly ${DESTDIR}/${tempfoo}.wrap /tmp/${tempfoo}.wrap.sh \
 "${tempfoo} Package" "./${WSNAME}"
rm -rf "${DESTDIR}"
