#!/bin/sh

set -e
#set -x

BASEDIR="${BASEDIR:-$(dirname -- $0)}"
BASEDIR="`readlink -f -- "${BASEDIR}"`"

tempfoo=`basename "${0}"`

. "${BASEDIR}/makeargs/${tempfoo}.sub"

DESTDIR="`mktemp -d -t "${tempfoo}"`" || exit 1
export DESTDIR

WRAPDIR="`mktemp -d "${DESTDIR}/${tempfoo}.wrap"`" || exit 1
export WRAPDIR

WSNAME="install.sh"

WRAPSCRIPT="${WRAPDIR}/${WSNAME}"
export WRAPSCRIPT

echo "set -e" > "${WRAPSCRIPT}"
chmod 755 "${WRAPSCRIPT}"

IFS=$'\n'
MAKE_ARGS=`gen_make_args`

if [ -e "${BASEDIR}/before/${tempfoo}.sub" ]
then
  . "${BASEDIR}/before/${tempfoo}.sub"
fi

make ${MAKE_ARGS} DESTDIR="${DESTDIR}" "${@}" "${tempfoo}"

if [ -e "${BASEDIR}/after/${tempfoo}.sub" ]
then
  . "${BASEDIR}/after/${tempfoo}.sub"
fi

chmod 755 "${WRAPDIR}"

echo "echo \"${tempfoo} completed successfully.\"" >> "${WRAPSCRIPT}"

COMPRESS_CMD="xz -T0 -v" UNCOMPRESS_CMD="xz -T0 -d" ${BASEDIR}/makeself/makeself.sh \
 --xz --tar-quietly ${DESTDIR}/${tempfoo}.wrap /tmp/${tempfoo}.wrap.sh \
 "${tempfoo} Package" "./${WSNAME}"
rm -rf "${DESTDIR}"
