#!/bin/sh

PATH=/bin:/sbin:/usr/bin:${PATH}

set -e
#set -x

ntharg() {
  shift $1
  printf '%s\n' "$1"
}

firstnargs() {
  i=0
  nargs="${1}"
  shift
  while [ ${i} -lt ${nargs} ]
  do
    if [ ${i} -gt 0 ]
    then
      printf ' '
    fi
    printf '%s' "$1"
    shift
    i=$((${i} + 1))
  done
}

# Prints out the relative path between to absolute paths. Trivial.
#
# Parameters:
# $1 = first path
# $2 = second path
#
# Output: the relative path between 1st and 2nd paths
relpath() {
    local pos="${1%%/}" ref="${2%%/}" down=''

    while :; do
        test "$pos" = '/' && break
        case "$ref" in $pos/*) break;; esac
        down="../$down"
        pos=${pos%/*}
    done

    echo "$down${ref##$pos/}"
}

hasarg() {
  farg="${1}"
  shift
  while [ ${#} -gt 0 ]
  do
    if [ "${1}" = "${farg}" ]
    then
      return 0
    fi
    shift
  done
  return 1
}

tgt="`ntharg ${#} "${@}" | sed "s|^${DESTDIR}|\$\{DESTDIR\}|"`"
case "${1}" in
"-d")
  printf 'install ' >> "${WRAPSCRIPT}"
  firstnargs $((${#} - 1)) "${@}" >> "${WRAPSCRIPT}"
  printf ' "%s"\n' "${tgt}" >> "${WRAPSCRIPT}"
  ;;
"-l")
  printf 'install ' >> "${WRAPSCRIPT}"
  src1="`ntharg $((${#} - 1)) "${@}" | head -c 1`"
  if [ "${src1}" = "/" ]
  then
    src="`ntharg $((${#} - 1)) "${@}" | sed "s|^${DESTDIR}|\$\{DESTDIR\}|"`"
    firstnargs $((${#} - 2)) "${@}" >> "${WRAPSCRIPT}"
    printf ' "%s" "%s"\n' "${src}" "${tgt}" >> "${WRAPSCRIPT}"
  else
    firstnargs $((${#} - 1)) "${@}" >> "${WRAPSCRIPT}"
    printf ' "%s"\n' "${tgt}" >> "${WRAPSCRIPT}"
  fi
  ;;
*)
  nsrcs=0
  while [ ${nsrcs} -lt $((${#} - 1)) ]
  do
    psrc="`ntharg $((${#} - ${nsrcs} - 1)) "${@}"`"
    if [ ! -e "${psrc}" ]
    then
      break
    fi
    nsrcs=$((${nsrcs} + 1))
  done
  if [ ${nsrcs} -gt 0 ]
  then
    _nsrcs="${nsrcs}"
    if hasarg "-s" "${@}"
    then
      strip=1
    else
      strip=0
    fi
    while [ ${_nsrcs} -gt 0 ]
    do
      src="`ntharg $((${#} - ${_nsrcs})) "${@}"`"
      src_bn="`basename "${src}"`"
      src_rp="`realpath "${src}"`"
      src_dir="`dirname "${src_rp}"`"
      src_dirhash="`md5 -q -s "${src_dir}"`"
      src_ndir="${WRAPDIR}/${src_dirhash}"
      if [ ! -e "${src_ndir}" ]
      then
        mkdir "${src_ndir}"
      fi
      src_n="${src_ndir}/${src_bn}"
      src_nshrt="${src_dirhash}/${src_bn}"
      if [ ${strip} -eq 0 ]
      then
        install -m 644 "${src}" "${src_n}"
      else
        install -m 644 -s "${src}" "${src_n}"
      fi
      printf 'install ' >> "${WRAPSCRIPT}"
      firstnargs $((${#} - ${nsrcs} - 1)) "${@}" >> "${WRAPSCRIPT}"
      printf ' "%s"' "${src_nshrt}" >> "${WRAPSCRIPT}"
      _nsrcs=$((${_nsrcs} - 1))
      printf ' "%s"\n' "${tgt}" >> "${WRAPSCRIPT}"
    done
  else
    printf 'install ' >> "${WRAPSCRIPT}"
    firstnargs $((${#} - 1)) "${@}" >> "${WRAPSCRIPT}"
    printf ' "%s"\n' "${tgt}" >> "${WRAPSCRIPT}"
  fi
  ;;
esac
exec echo install "${@}"
